### ISSUE TITLE
用户个人页面“订阅TA的消息”链接前的图标应为中性色

### ISSUE THREAD

**Issue by riophae** [ispacekid/space-fanfou#34]
这个图标应该尽量采用中性色，否则会与部分用户个性鲜明的色彩搭配发生冲突

**Comment by LitoMore** [comment]
橙色就是rss的代表色，橙色也算是中性色之一，如果当前颜色不够合适，建议采用扁平化的rss图标再稍微调整一下颜色会更好一些

**Comment by riophae** [comment]
希望和侧栏顶部的灰色图标统一起来

**Comment by LitoMore** [comment]
订阅按钮已经不存在了。
Closing.
